apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: oracle
spec:
  selector:
    app: oracledb-21c-entpr
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521