apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracledb-21c-entpr
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: oracledb-21c-entpr
  serviceName: oracledb-21c-entpr-service
  replicas: 1
  template:
    metadata:
      labels:
        app: oracledb-21c-entpr
    spec:
      serviceAccountName: oracle-service-account
      volumes:
        - name: oracle-pvc
          persistentVolumeClaim:
            claimName: efs-pvc-oracle
      containers:
        - name: oracledb-21c-entpr
          image: container-registry.oracle.com/database/enterprise:latest
          ports:
            - containerPort: 1521
              name: db-port
            - containerPort: 5500
              name: em-port
          env:
            - name: ORACLE_PWD
              value: Password123
          volumeMounts:
            - name: oracle-pvc
              mountPath: /data
          resources:
            requests:
              memory: "8Gi"
              cpu: "6"
            limits:
              memory: "16Gi"
              cpu: "8"